config/routes.rb
Rails.application.routes.draw do
    root to: "top#index"
    get "sign_in" => "sessions#new", as: :sign_in
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy" 
  
    resources :users, except: [:edit, :update]
    resources :articles
    resource :account, only: [:show, :edit, :update] 
    resource :password, only: [:show, :edit, :update]
  
     namespace :admin do 
       root "top#index"
       resources :users, except: [:new, :create ] 
     end
  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user 
  mount_uploader :image, ImageUploader
  
  with_options presence: true do 
    validates :title 
    validates :body
    validates :image 
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  layout "sign_in"
  before_action :authorize_user, except: [:index]
  
  def index
    @articles = Article.all 
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new 
  end

  def edit
     @article = Article.find(params[:id])
     if @article.user != current_user
       flash.alert = "不正なアクセスをしています"
       redirect_to :articles 
     end
  end
  
  def create 
    @article = Article.new(article_params)
    @article.user_id = current_user.id 
    if @article.save
      flash.notice = "投稿内容を登録しました。"
      redirect_to (article_path(@article))
    else 
      flash.now.alert = "投稿内容を登録できませんでした。"
      render action: "new"
    end
  end
  
  def update 
    @article = Article.find(params[:id])
    @article.assign_attributes(article_params)
    if @article.save 
      flash.notice = "投稿内容を更新しました。"
      redirect_to @article
    else 
      render action: "edit"
    end
  end
  
  def destroy 
    article = Article.find(params[:id])
    article.destroy!
    flash.notice = "投稿を削除しました。"
    redirect_to :articles
  end
  
  private def authorize_user
    unless current_user
      flash.alert = "ログインしてください。"
      redirect_to :sign_in
    end
  end
  
  private def article_params
    params.require(:article).permit(:title, :body, :image)
  end
end

app/views/articles/edit.html.erb
<% @title = "投稿編集" %>
<div class="page-title">
<h1>投稿</h1>
</div>

 <% if @article.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @article, url: :article do |f| %>
          <%= render "shared/form", f: f %>
          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<% @title = "投稿一覧" %>
<div class="page-title">
<h1>投稿一覧</h1>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @articles.each do |article| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to article_path(article) do %>
                  <img src="<%= article.image %>">
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <% if  article.user.image? %>
                      <img src="<%= article.user.image %>" class: "profile_image" alt="ユーザーアイコン">
                    <% else %>
                      <img src="/assets/no-image.png" class: "profile_image" alt="ユーザーアイコン" >
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to article.user.username, user_path(article.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<% @title = "新規投稿" %>
<div class="page-title">
<h1>新規投稿</h1>
</div>
 <% if @article.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @article, url: :articles do |f| %>
          <%= render "shared/form", f: f %>
          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<% @title = "投稿" %>
<div class="page-title">
  <h1><%= @title %></h1>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="<%= @article.image %>">
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @article.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>投稿内容</th>
                </tr>
                <tr>
                  <td><%= simple_format @article.body %></td>
                </tr>
              </table>
              <% if @article.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_article_path(@article), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @article.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @article.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@article.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @article.user.username %> さんのプロフ 
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>