config/routes.rb
Rails.application.routes.draw do
    root to: "top#index"
    get "sign_in" => "sessions#new", as: :sign_in
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy" 
  
    resources :users, except: [:edit, :update]
    resources :articles
    resource :account, only: [:show, :edit, :update] 
    resource :password, only: [:show, :edit, :update]
  
     namespace :admin do 
       root "top#index"
       resources :users, except: [:new, :create ] 
     end
  
end

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; 2020 Catalks</p>
</footer>

app/views/shared/_form.html.erb
<div class="field">
  <%= f.label :title, "タイトル", class: "label" %>
  <%= f.text_field :title, class: "input" %>
</div>

<div class="field">
 <%= f.label :body, "内容", class: "label" %>
 <%= f.text_area :body, class: "textarea" %>
</div>

<div class="field">
  <%= f.label :image, "添付", class: "label" %>
  <%= f.file_field :image, class: "input" %>
</div>

app/views/shared/_header.html.erb
<header>
  <% if current_user %>
    <span class="logo-mark"><%= link_to "Catalks", :articles %></span>
  <% else %>
    <span class="logo-mark"><%= link_to "Catalks", :root %></span>
  <% end %>
  
  <%= content_tag(:span, flash.notice, class: "notice") if flash.notice %>
  <%= content_tag(:span, flash.alert, class: "alert") if flash.alert %>
  
  <% if current_user %>
    <%= link_to "ログアウト", :session, method: :delete, class: "links" %>
    <%= link_to "アカウント", :account, class: "links" %>
    <% if current_user.administrator? %>
      <%= link_to "管理ページ", :admin_root, class: "links" %>
    <% end %>
    <div class="login-navbar" %>
    <div class="navbar-item">
      <%= link_to "投稿一覧", articles_path, class: "navbar-item button is-warning is-light" %>
    </div>
    <div class="navbar-item">
      <%= link_to "新規投稿", new_article_path, class: "navbar-item button is-warning is-light" %>
    </div>
    <div class="navbar-item">
      <%= link_to "ユーザー一覧", users_path, class: "navbar-item button is-warning is-light" %>
    </div>
    </div>
  <% else %>
    <div class="logout-navbar">
      <div class="navbar-item">
        <%= link_to "投稿一覧", articles_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-item">
        <%= link_to "ユーザー一覧", users_path, class: "navbar-item button is-warning is-light" %>
      </div>
    </div>
  <% end %> 
</header>