config/routes.rb
Rails.application.routes.draw do
    root to: "top#index"
    get "sign_in" => "sessions#new", as: :sign_in
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy" 
  
    resources :users, except: [:edit, :update]
    resources :articles
    resource :account, only: [:show, :edit, :update] 
    resource :password, only: [:show, :edit, :update]
  
     namespace :admin do 
       root "top#index"
       resources :users, except: [:new, :create ] 
     end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  layout "sign_in"
  before_action :authorize_user
  
  def show
    @user = current_user 
   
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    @user.assign_attributes(account_params)
    if @user.save
      flash.notice = "アカウントを更新しました。"
      redirect_to :account
    else
      flash.now.alert = "アカウントを更新できませんでした。"
      render action: "edit"
    end
  end
  
  private def authorize_user
    unless current_user
      flash.alert = "ログインしてください。"
      redirect_to :sign_in
    end
  end
  
  private def account_params
    params.require(:user).permit(:username, :email, :profile, :image)
  end
  
  
  
end

app/views/accounts/edit.html.erb
<% @title = "アカウント編集" %>
<div class="page-title">
  <h1><%= @title %></h1>
</div>

 <% if @user.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        
        <%= form_for @user, url: account_path do |f| %>
        
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %> 
          </div>
          
          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>
            
          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label "プロフィール画像", class: "label" %>
            <%= f.file_field :image, class: "input" %>
          </div>
          
          <div>
          <%= f.submit "更新", class: "button is-success" %>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/accounts/show.html.erb
<% @title = "マイアカウント" %>
<div class="page-title">
  <h1><%= @title %></h1>
</div>
<div class="password-link">
  <%= link_to "パスワード変更", :edit_password %> 
</div>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <% if  @user.image? %>
                <img src='<%= @user.image %>' class: "profile_image is-rounded" alt="ユーザーアイコン">
              <% else %>
                <img src="/assets/no-image.png" class: "profile_image is-rounded" alt="ユーザーアイコン" >
              <% end %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", :edit_account, class: "button is-primary" %>
                </td>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.articles.each do |article| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to article_path(article) do %>
                  <% if  article.image? %>
                <img src="<%= article.image %>" alt="ユーザーアイコン">
              <% else %>
                <img src="/assets/no-image.png" alt="ユーザーアイコン" >
              <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to article_path(article), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                    <%= link_to edit_article_path(article), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to article_path(article), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>